Add image reference for `create-upgrade-prs` cronjob, Update go to `v1.20.5`
gardener/machine-controller-manager-provider-vsphere pull request #65
Opened 2023-06-22 15:45 UTC by rishabh-11

**What this PR does / why we need it**:
This PR specifies the golang container image to be used by the create-upgrade-prs cronjob to run the set_dependency_version script.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement user
NONE
```

2023-06-22 15:46 UTC, elankath approved these changes
so patch version change needed in Dockerfile

2023-06-22 15:50 UTC, rishabh-11 commented
> so patch version change needed in Dockerfile

This has nothing to do with the pipeline cronjob. I did this because I was upgrading the go version to `1.20.5`.

2023-06-22 16:54 UTC, briantopping requested changes
Thanks for this PR. The use of `1.20` is not the same as `1.20.0`, the former is an alias to the latest in the `1.20` series. At this maturity level of the code, we need to reduce maintenance costs more than we need binary reproducibility of specific tags or commits. Please restore the versions in the patch as appropriate.

2023-08-17 05:03 UTC, rishabh-11 commented
/close
Not needed anymore. The pipeline job is working fine for vsphere

2023-08-17 05:03 UTC, closed without merging